### PR TITLE
 fix: #34 

### PR DESCRIPTION
**Pull request by PaulLerner**
my editor deleted some spaces at the end of the line in README for some reason...

### CODE REVIEW

**Comment by hbredin** [comment]
Thanks. 

I realize I was not very clear: I actually had something more drastic in mind. 
I thought we could do the cropping directly in the `train`, `development`, and `test` methods.

As it is right now, `stats(subset=train)` and `train()` would disagree on the total annotation duration.

Does it make sense?

**Comment by PaulLerner** [comment]
So instead of yielding `self.preprocess(item)` I should first crop `item['annotation']` ?
Shouldn't it be rather in the `self.preprocess` method (which is quite obscure to me...) ?

**Comment by hbredin** [comment]
Thinking about this a bit more, maybe this behavior should only be supported for custom protocols defined in `database.yml` (and not for protocols provided by pyannote.database plugins). 

So, the logic should go in this function: https://github.com/pyannote/pyannote-database/blob/1deac46907d86f63d5aaf4d48ae3e3744a6ab7cf/pyannote/database/custom.py#L100

**Comment by PaulLerner** [comment]
closing (see #36 )

**Pull request closed without merging**
