### PR TITLE
BREAKING: one configuration file to rule them

### PR DESCRIPTION
**Pull request by hbredin**
Merge all three configuration files (`~/.pyannote/db.yml`, `~/.pyannote/custom.yml`, and `~/.pyannote/meta.yml`) into a unique `~/.pyannote/database.yml`.

This will lead to a major 2.0 release as this breaks compatibility with the 1.x branch.

### CODE REVIEW

**Comment by hbredin** [comment]
cc @pkorshunov 

If you have five minutes to try this, I would be interested in getting your feedback on this.
The only thing you should have to do is create a new `~/.pyannote/database.yml` gathering all 3 old configuration files. 

`README` has been updated with description of this new file.
It now has two sections: 
* `Databases` to describe where to find audio files
* `Protocols` to describe custom and meta-protocols

**Comment by pkorshunov** [comment]
sorry we had two days holidays and I couldn't get to my computer with all the kids around me.
Anyway, I just started a training with this updated configuration. I will let you know how it goes.

**Comment by pkorshunov** [comment]
This new config file is working well. I started experiments that have all the components: a meta protocol, custom db interface, and several paths to databases. Everything seems to work fine, so I think you can merge it.

**Comment by hbredin** [comment]
Thanks for beta-testing! Merged.

**Pull request merged**
