### PR TITLE
Add LabelMapper class for mapping labels

### PR DESCRIPTION
**Pull request by MarvinLvn**
New class to map input labels to some output labels !

### CODE REVIEW

**Comment by hbredin** [comment]
Thanks @MarvinLvn 
I pushed an updated version of this mapper.
Can you please confirm this still does what you had in mind before I merge it?

**Comment by hadware** [comment]
Note to @MarvinLvn: don't forget to bump the pyannote.database version in the pyannote.audio package when you're done.

**Comment by MarvinLvn** [comment]
@hbredin : works like a charm after adding self to access class attributes

**Comment by hbredin** [comment]
Great! I am going to merge it.

Do you plan any new addition to `pyannote.database` in the near future or can I prepare a new release?

**Pull request merged**
