### PR TITLE
feat: make paths in database.yml (optionally) relative. Closes #38

### LINKED ISSUE #38: Feature: make paths in database.yml (optionally) relative
I think it would be nice to be able to indicate relative paths in database.yml. This way, we could easily share plumcot corpus for example.
We could easily implement it by testing if the path (to e.g. RTTM file) `is_absolute()` and then concatenate it to the path of `PYANNOTE_DATABASE_CONFIG` if it's not.

### PR DESCRIPTION
**Pull request by PaulLerner**

### CODE REVIEW

**Comment by hbredin** [comment]
Thanks. Can you please also update `README.md` to mention this feature?

**Comment by PaulLerner** [comment]
done :)

**Comment by hbredin** [comment]
I took over this PR and merged it here: 
https://github.com/pyannote/pyannote-database/commit/1c9443bdea0e41694abbc7fdbcdc29eea8849398

You still appear as co-author, though...

Can you confirm this fixes #38?

**Comment by PaulLerner** [comment]
tested !

```bash
(pyannote) paul@paullerner:~/Documents/limsi/pyannote-db-plumcot$ export PYANNOTE_DATABASE_CONFIG=$PWD/Plumcot/data/database.yml
(pyannote) paul@paullerner:~/Documents/limsi/pyannote-db-plumcot$ cd ..
(pyannote) paul@paullerner:~/Documents/limsi$ stats.py HarryPotter.SpeakerDiarization.0
gettings stats from HarryPotter.SpeakerDiarization.0.train...
annotated 5281.429999999969
annotation 2836.8099999998867
```

**Pull request closed without merging**
